# Generated by Django 2.2.9 on 2020-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200824_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Ваше мнение важно для автора', max_length=200, verbose_name='Текст комментария'),
        ),
    ]
