# Generated by Django 2.2.9 on 2020-08-26 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200826_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Рассказ о себе поможет другим пользователям лучше узнать Вас', max_length=500, null=True, verbose_name='Опишите себя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL, verbose_name='Ваше имя для остальных пользователей')),
            ],
        ),
    ]
