# Generated by Django 2.2.9 on 2020-08-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200831_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_author',
            name='dislike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='profile_author',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post'),
        ),
    ]
