# Generated by Django 2.2.9 on 2020-08-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20200831_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_author',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='profile_author',
            name='like',
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
